#!/usr/bin/env bash
# script that installs nginx on server
# configures it to listen at port 80
# sets Hello World! as default page

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
service nginx start