#!/usr/bin/env bash
# script that installs nginx on server
# configures it to listen at port 80
# sets Hello World! as default page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
service nginx start