#!/usr/bin/env bash
# script that installs nginx on server
# configures it to listen at port 80
# sets Hello World! as default page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i 's/\s*server_name _;/&\n\trewrite ^\/redirect_me.*$ https:\/\/example.com permanent\nerror_page 404 /custom_404.html;/' /etc/nginx/sites-available/default
sudo service nginx start