#!/usr/bin/env bash
# script that installs HAProxy and configures it as load balancer

sudo apt-get install --no-install-recommends -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*
sudo tee -a '/etc/haproxy/haproxy.cfg' <<ADDTHIS
frontend tomyservers
        mode http
        bind :80
        default_backend karenbuilds

backend karenbuilds
        mode http
        balance roundrobin
        server web-01 54.144.142.198:80 check
        server web-02 34.207.222.12:80 check
ADDTHIS
sudo service haproxy restart