#!/usr/bin/env bash
# prints "Best School" ten times, "bad luck" instead
# at position 4, "good luck" at position 8
i=1
while [ $i -lt 11 ]
do
if [ $i -eq 4 ]
then
	echo "bad luck"
elif [ $i -eq 8 ]
then
	echo "good luck"
else
	echo "Best School"
fi
((i++))
done
