#!/usr/bin/env bash
# prints the numbers 1 to 20, bad luck from China after number 4,
# bad luck from Japan after 9 and bad luck from italy after 17

i=1
while [ $i -lt 21 ]
do
echo $i
case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
esac
((i=i+1))
done
